server:
  port: 8100

spring:
  application:
    name: hotel

  datasource:
    url: jdbc:h2:mem:hotel
    username: sa

    #url: jdbc:mysql://127.0.0.1:3306/hotel
    #username: root
    password:

    initialization-mode: always
    schema: classpath*:schema.sql
    data: classpath*:data.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console